# Generated by Django 6.0.7 on 2026-08-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='cartificate_number',
            new_name='certificate_number',
        ),
    ]
